### ISSUE TITLE
Swift Package Manager Support

### ISSUE THREAD

**Issue by ragzy15** [CleverTap/CTNotificationContent#10]
Please provide support for Swift Package Manager, it is well integrated with Xcode than Cocoapods. 
We already use CleverTap SDK as a Swift Package andIt would be great to be able to use it with this as well.

**Comment by Aditi3** [comment]
Thank you for submitting the feature request. I have added this to our roadmap. 

Please allow us some time to get back to you with an update.

**Comment by ragzy15** [comment]
@Aditi3 any update regarding this?

**Comment by Aditi3** [comment]
Follow the progress at https://github.com/CleverTap/CTNotificationContent/tree/support-swift-pm.

**Comment by ragzy15** [comment]
@Aditi3 any update on release timeline?

**Comment by Aditi3** [comment]
@ragzy15 We're shipping this today!

**Comment by ragzy15** [comment]
Thank you 😊
