### ISSUE TITLE
SDK does not trigger userDidReceive or userDidPerformAction on user tap action in NotificationContent target

### ISSUE THREAD

**Issue by manish-practo** [CleverTap/CTNotificationContent#23]
## Steps to reproduce

- Open swift example project and run the `NotificationContent` target
- Put the app in background 
- Create a carousel (or any other) notification with deeplinks or add custom json properties (including deeplinks)
- Send it from Clevertap dashboard
- Long press to expand the notification (can see the images)
- Tap on the notification (or tap outside to collapse the notification)
- App opens but neither `userDidReceive` nor `userDidPerformAction` get's triggered

### Note
`userDidPerformAction` does get's trigger when carousel's page slides. 

## Another issue
There are times when we need custom values from notification for mapping on specific action. But since none of the above mentioned function get's triggered, we are unable to get any data.
One good example is deeplink.

**Comment by akashvercetti** [comment]
@manish-practo currently, clicking on the notification opens a deeplink if provided, or the parent app. However if you need to get a method callback for `userDidPerformAction` or `userDidReceive` , you can define notification actions in your app like this doc snippet: https://github.com/CleverTap/CTNotificationContent#configure-your-app-for-push-and-add-a-notification-content-extension-target
