### ISSUE TITLE
Can provide more custom actions with different notifications?

### ISSUE THREAD

**Issue by archerx3** [CleverTap/CTNotificationContent#3]
RT, Can you provide more custom actions with more different notification?

Need custom more actions for different notification, and different handle for different action.

**Comment by Aditi3** [comment]
Hey @archerx3, Could you please reach out to the CleverTap support team at support@clevertap.com with your use-case and more details.

**Comment by archerx3** [comment]
I mean in code, provide the API to custom actions for different notifications.
