### ISSUE TITLE
Tempates are not rendering with pt_json Custom key-value pairs

### ISSUE THREAD

**Issue by nirav-infostretch** [CleverTap/CTNotificationContent#30]
We are using below SDK
clevertap-react-native : 0.9.5
CTNotificationService : 0.1.5
CTNotificationContent : 0.2.4
react-native : 0.64.4

When we use separate Custom key-value pairs from dashboard, templates are rendering correcting.
When we use json with pt_json key, templates are not rendering correctly.

We found one issue in sdk, it is crashing at below line;
https://github.com/CleverTap/CTNotificationContent/blob/0d0b103ea695dc34033fd4347a02e6cfcad8f811/CTNotificationContent/CTNotificationViewController.m#L161

It is fixed by doing below change 
self.jsonString = [self createJSONData:content[kJSON]];
at 
https://github.com/CleverTap/CTNotificationContent/blob/0d0b103ea695dc34033fd4347a02e6cfcad8f811/CTNotificationContent/CTNotificationViewController.m#L179

Can you please fix this issue ?

**Comment by nishant-clevertap** [comment]
Hi @nirav-infostretch

Can you test the below format and let me know if it works or not:
```
pt_id: pt_rating
pt_json: {"pt_title": "Title","pt_msg": "Message","pt_default_dl": "uimdl://uatim.com/FLIGHT_EARN","pt_dl1": "uimdl://uatim.com/FLIGHT_EARN","pt_bg": "#FFFFFF"}
```
Just add the value of pt_json in single line without any new line.

**Comment by nishant-clevertap** [comment]
Hi @nirav-infostretch, Have you tried the above approach?

**Comment by nishant-clevertap** [comment]
Hi @nirav-infostretch,
The approach suggested will work with pt_json custom key-value pairs. If you still face the issue, do reopen the issue with console logs if possible. Thanks.
