### ISSUE TITLE
Not able to dismiss Rich push notification on expanded 

### ISSUE THREAD

**Issue by subramanyamios** [CleverTap/CTNotificationContent#33]
Created a Rich push notification supported by Clevertap (Timer Template), and it reaches the device then if expand and click on it opens the app but action has not been sent to the UNUserNotificationCenter delegate and the notification remains in the notification center.

**Comment by subramanyamios** [comment]
@nishant-clevertap Any help from your side? Please

**Comment by nishant-clevertap** [comment]
@subramanyamios 
Can you share your AppDelegate file code to check if UNUserNotificationCenter delegate is correctly set or not? Also what deeplink you are using to open on click?

**Comment by subramanyamios** [comment]
@nishant-clevertap 

It's working on tapping the notification, the issue is only when you expand it. Here I mean to say we set delegate `UNUserNotificationCenter.current()`  correctly and getting call backs to this methosd `func userNotificationCenter(_ center: UNUserNotificationCenter,
                                didReceive response: UNNotificationResponse,
                                withCompletionHandler completionHandler: @escaping () -> Void) {`
                                
The main issue is dismissing the push notification on the expanded and click state, it still remains in the notification center.

**Comment by nishant-clevertap** [comment]
@subramanyamios 
Can you share a video for the issue which you are facing? Also share below things:
1. Which SDKs you are using with version number?
2. How are you integrating CleverTap SDK - auto or manual?
3. AppDelegate file if possible.

**Comment by subramanyamios** [comment]
@nishant-clevertap 

https://github.com/CleverTap/CTNotificationContent/assets/8524080/f93fdd43-f217-4a9e-9398-e0beebb75bef

1. SDK versions
CleverTap SDK - 4.2.2
CTNotificationContent 0.2.4
CTNotificationService 0.1.5

2. Integrated with Swift Package Manager - Version  rules - exact version
3. Can't disclose

**Comment by nishant-clevertap** [comment]
Hi @subramanyamios 
Thanks for raising this. We have reproduced this at our end and working on fix for this. We will update you when fix will be released.

**Comment by nishant-clevertap** [comment]
Hi @subramanyamios 
We have added a fix for this in latest release: https://github.com/CleverTap/CTNotificationContent/releases/tag/0.2.5
Let us know if your issue is resolved after updating to v0.2.5.
Thanks.
