### ISSUE TITLE
iOS Rich Push notifications -  Auto Carousel not shown for the very first time tap

### ISSUE THREAD

**Issue by subramanyamios** [CleverTap/CTNotificationContent#34]
Hi @akashvercetti @AishwaryaNanna @nishant-clevertap 

We are using the CTNotificationContent for Rich Push Notifications. Added all the required key values for the Auto Carousel template. The issue the Auto carousel is shown up the second time tap not on the first time long press for the same notification.

Configuration details:
Used SPM to install the CTNotificationContent extension and on the latest version.
Please do needful.

Thanks

**Comment by nishant-clevertap** [comment]
Hi @subramanyamios 
Can you share the video of the issue your are facing?

**Comment by subramanyamios** [comment]
@nishant-clevertap 
Please check
https://github.com/CleverTap/CTNotificationContent/assets/8524080/50278fd2-a02c-463d-8316-1a4e299759f6

**Comment by nishant-clevertap** [comment]
@subramanyamios The video shared by you does not have enough clarity. Try recording the video some seconds before tapping the first time so that we can see the actual steps which you are doing to reproduce it, starting from when you received the notification.

**Comment by subramanyamios** [comment]
@nishant-clevertap 
Split into two due to limited size for uploading
https://github.com/CleverTap/CTNotificationContent/assets/8524080/8e543307-14cf-481b-a11b-ff898911d170

https://github.com/CleverTap/CTNotificationContent/assets/8524080/23018e6c-cbad-4d58-8619-72e64f7cd595

**Comment by subramanyamios** [comment]
Hi, @nishant-clevertap Any update?

**Comment by nishant-clevertap** [comment]
Hi @subramanyamios,
We have checked the behaviour in our sample app and it is working fine. As I can see from the video shared you are getting RCB's image on first expand and other image on second expand. Can you share your payload (keys and values which you are using) so that we can test it on our sample app? 
Also Are you getting this behaviour 5/5 times?

**Comment by subramanyamios** [comment]
@nishant-clevertap 

issue - no carousel on tap for the first time ever.
1/ 5 times

Please check the custom key-value pairs

**KEY**                                                    **Value**
pt_id                                                           pt_carousel
pt_title                                                       Autocrousal
pt_msg                                                      Auto carousal message
pt_msg_summary                                    Auto carousal message summary
pt_dl1                                                         jiovootviacom18://jiovoot/playback/avr/3707672
pt_img1                                                     https://s3.amazonaws.com/ct-demo-images/landscape-1.jpg
pt_img2                                                     https://s3.amazonaws.com/ct-demo-images/landscape-2.jpg
pt_img3                                                     https://1000logos.net/wp-content/uploads/2022/02/RCB-logo-1536x864.png
pt_bg                                                         #E9967A

**Comment by subramanyamios** [comment]
@nishant-clevertap 

have you tried with the above payload?

**Comment by subramanyamios** [comment]
Hi @nishant-clevertap 

Update, please

**Comment by nishant-clevertap** [comment]
Hi @subramanyamios 
We have tested with your payload and found same behaviour as you were getting, ie on first expand a default view area will appear and then your carousel. We are working on the actual cause and fix for this. We will update you here with the details after investigation is completed.

**Comment by subramanyamios** [comment]
Hi @nishant-clevertap 

Please update on this.

Thanks

**Comment by nishant-clevertap** [comment]
Hi @subramanyamios 
We have added fix for this, and will be probably doing release by next week. I will update you when release is done.
Thanks.

**Comment by subramanyamios** [comment]
@nishant-clevertap 
Thank you!

**Comment by nishant-clevertap** [comment]
Hi @subramanyamios 
We have added a fix for this in latest release: https://github.com/CleverTap/CTNotificationContent/releases/tag/0.2.5
Let us know if your issue is resolved after updating to v0.2.5.
Thanks.
