### ISSUE TITLE
Getting No such module 'CTNotificationContent' error

### ISSUE THREAD

**Issue by kishoretheju** [CleverTap/CTNotificationContent#5]
<img width="1094" alt="screenshot 2018-11-19 at 7 36 40 pm" src="https://user-images.githubusercontent.com/6185202/48711974-9d841880-ec32-11e8-96ee-ed8acbb5a931.png">

**Comment by Aditi3** [comment]
Please refer: https://github.com/CleverTap/CTNotificationService/issues/6
