### ISSUE TITLE
"View In App" action button tap does not open app.

### ISSUE THREAD

**Issue by kishoretheju** [CleverTap/CTNotificationContent#6]
"View In App" action button tap not invoking callback function 
`-(void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)(void))completionHandler`

I tried by changing 
`[UNNotificationAction actionWithIdentifier:@"action_3" title:@"View In App" options:UNNotificationActionOptionNone]`

to

`[UNNotificationAction actionWithIdentifier:@"action_3" title:@"View In App" options:UNNotificationActionOptionForeground]`

Tapping on "View In App" should open invoke the callback for me to handle the deeplink right? Am i missing something here.

**Comment by kishoretheju** [comment]
I will try it and get back.

**Comment by kishoretheju** [comment]
How do i pass the action data to app?

**Comment by kishoretheju** [comment]
Got it, had to put to the same deeplink url in call to action url for the button.

**Comment by Aditi3** [comment]
Awesome, thanks for letting us know.
