### ISSUE TITLE
Built in UI for detail and title labels are not adapting to dark mode

### ISSUE THREAD

**Issue by jazminebarroga** [CleverTap/CTNotificationContent#9]
When the phone’s appearance is set to dark mode, the title label color remains black while the detail label color remains gray with a black background

**Comment by Aditi3** [comment]
Hi @jazminebarroga 

Thank you so much for bringing this up. We'll see how to handle the title color for Dark Mode in our next release. Right now, if you want to change the background color of the push notification, then simply navigate to the Notification Content Storyboard and update the Background property of the View. 

Hope this helps!
